[tool.poetry]
name = "signals"
version = "0.1.22"
description = ""
authors = ["gravegrow <gravegrow@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytest = "^7.4.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
